//auth constants
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REFRESH_SESSION = "REFRESH_SESSION";

//socket constants
export const CONNECT_SOCKET = "CONNECT_SOCKET";
export const DISCONNECT_SOCKET = "DISCONNECT_SOCKET";

//user constants
export const GET_USER = "GET_USER";
export const GET_DOCTORS = "GET_DOCTORS";
export const IS_LOADING = "IS_LOADING";
export const IS_DONE = "IS_DONE";
export const ADD_APPOINTMENT_SUCCESS = " ADD_APPOINTMENT_SUCCESS";
export const REMOVE_APPOINTMENT_SUCCESS = "REMOVE_APPOINTMENT_SUCCESS";
//doctor constants
export const SET_DOCTORS = "SET_DOCTORS";
export const DOCTORS_LOADING_IS_DONE = "DOCTORS_LOADING_IS_DONE";
export const DOCTORS_LOADING = "DOCTORS_LOADING";
//patient constants
export const SET_PATIENTS = "SET_PATIENTS";
export const PATIENTS_LOADING_IS_DONE = "PATIENTS_LOADING_IS_DONE";
export const PATIENTS_LOADING = "PATIENTS_LOADING";
//clinic constants
export const DONE_LOADING_CLINICS = "DONE_LOADING_CLINICS";
export const LOADING_CLINICS = "LOADING_CLINICS";
export const SET_CLINICS = "SET_CLINICS";

//chat constants
export const CREATE_ROOM_REQUEST = "CREATE_ROOM_REQUEST";
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_ERROR = "CREATE_ROOM_ERROR";
export const JOIN_ROOM_REQUEST = "JOIN_ROOM_REQUEST";
export const JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS";
export const JOIN_ROOM_ERROR = "JOIN_ROOM_ERROR";
export const SET_MESSAGE_NOTIFICATION = "SET_MESSAGE_NOTIFICATION";
